#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

missing=0

check_cmd() {
  if command -v "$1" >/dev/null 2>&1; then
    echo "[OK] $1"
  else
    echo "[MISS] $1"
    missing=1
  fi
}

echo "== Apple build environment check =="
check_cmd xcodebuild
check_cmd flutter
check_cmd pod

if command -v xcode-select >/dev/null 2>&1; then
  echo "Xcode path: $(xcode-select -p 2>/dev/null || true)"
fi

if command -v xcodebuild >/dev/null 2>&1; then
  xcodebuild -version || true
  xcodebuild -license status || true
fi

if command -v flutter >/dev/null 2>&1; then
  flutter --version
  flutter doctor -v
fi

if [ ! -d "ios" ]; then
  echo "[INFO] ios/ is missing. It will be generated by tools/build_ios.sh."
else
  echo "[OK] ios/ exists"
fi

if [ ! -d "macos" ]; then
  echo "[WARN] macos/ is missing."
else
  echo "[OK] macos/ exists"
fi

if [ "$missing" -ne 0 ]; then
  echo "Environment is incomplete. Install the missing tools above."
  exit 1
fi

echo "Environment check finished."
